swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{userId}/accounts/month:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Current month accounts
      description: API for accounts list in current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: query
          name: month
          description: month from 1 to  12
          required: true
          type: number
          minimum: 1
          maximum: 12
      produces:
        - application/json
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
             $ref: '#/definitions/AccountResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error
  /user/{userId}/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions of specific account
      description: API for transactions list of specific account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
             $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error
  /user/{userId}/accounts/{accountId}/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update category in transaction
      description: API for updating category in a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
        - in: body
          name: category
          description: transaction category label
          required: true
          schema:
            type: object
            properties:
              categoryLabel: 
                type: string
                description: category label
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category updated successfully
          schema:
             $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: delete category in transaction
      description: API for deleting category in a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category deleted successfully
          schema:
             $ref: '#/definitions/CategoryDeleteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error          
  /user/{userId}/accounts/{accountId}/transactions/{transactionId}/transactionType:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction type
      description: API for updating transaction type
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
        - in: body
          name: transactionType
          description: transaction type label
          required: true
          schema:
            type: object
            properties:
              transactionTypeLabel: 
                type: string
                description: transaction type label
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category updated successfully
          schema:
             $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: delete type in transaction
      description: API for deleting type in a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction type deleted successfully
          schema:
             $ref: '#/definitions/TypeDeleteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error          
  /user/{userId}/accounts/{accountId}/transactions/{transactionId}/transactionNotes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction notes
      description: API for updating transaction notes
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
        - in: body
          name: transactionNotes
          description: transaction notes
          required: true
          schema:
            type: object
            properties:
              transactionNotes: 
                type: string
                description: transaction notes
      produces:
        - application/json
      responses:
        '200':
          description: Transaction notes updated successfully
          schema:
             $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: delete notes in transaction
      description: API for deleting notes in a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: userId
          type: string
          description: user id
          required: true
        - in: path
          name: accountId
          type: string
          description: account id
          required: true
        - in: path
          name: transactionId
          type: string
          description: transaction id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction notes deleted successfully
          schema:
             $ref: '#/definitions/NotesDeleteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Specified resource was not found 
        '500':
          description: Internal Server Error          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  AccountResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 215661
        currency:
          type: string
          example: $
        label:
          type: string
          example: Argent Bank Checking (x8349)
        balance:
          type: number
          example: 2082.79
        description:
          type: string
          example: Available Balance
  TransactionResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 315456
        date:
          type: string
          example: June 20th, 2020
        description:
          type: string
          example: Balance
        amount:
          type: number
          example: 5.50
        currency:
          type: string
          example: $
        transactionType:
          type: string
          example: Electronic
        category:
          type: string
          example: Food
        notes:
          type: string
  CategoryDeleteResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 315456
        date:
          type: string
          example: June 20th, 2020
        description:
          type: string
          example: Balance
        amount:
          type: number
          example: 5.50
        currency:
          type: string
          example: $
        transactionType:
          type: string
          example: Electronic
        notes:
          type: string
  TypeDeleteResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 315456
        date:
          type: string
          example: June 20th, 2020
        description:
          type: string
          example: Balance
        amount:
          type: number
          example: 5.50
        currency:
          type: string
          example: $
        category:
          type: string
          example: Food
        notes:
          type: string
  NotesDeleteResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: 315456
        date:
          type: string
          example: June 20th, 2020
        description:
          type: string
          example: Balance
        amount:
          type: number
          example: 5.50
        currency:
          type: string
          example: $
        transactionType:
          type: string
          example: Electronic
        category:
          type: string
          example: Food